#!/bin/sh

# pre-commit script to prevent merge markers from being committed.
# Adapted from here:
# https://jondowdle.com/2015/02/block-merge-conflicts-in-commits/
#
# This simply searches the files that you are about to commit for seven <, >, or
# = at the beginning of a line, followed by a space or the end of the line.

changed=$(git diff --cached --name-only)

if [[ -z "$changed" ]]; then
    exit 0
fi

echo $changed | xargs egrep '^[><=]{7}( |$)' -H -I --line-number

# If the egrep command has any hits - echo a warning and exit with non-zero status.
if [ $? == 0 ]; then
    echo "WARNING: You have merge markers in the above files. Fix them before committing."
    echo "         If these markers are intentional, you can force the commit with the --no-verify argument."
    exit 1
fi
